server:
  port: ${SERVER_PORT:5000}

debug: true

spring:
  application:
    name: scrumify

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/scrumify}
    username: ${SPRING_DATASOURCE_USERNAME:scrumify}
    password: ${SPRING_DATASOURCE_PASSWORD:@scrumify123}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:configuration/logback-spring.xml
